# Generated by Django 5.0.1 on 2026-01-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_device_sync_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='User email (primary identifier, matches Firebase users/{email})', max_length=254, unique=True)),
                ('password', models.CharField(help_text='User password (stored as plain text to match Firebase, consider hashing in production)', max_length=255)),
                ('access_level', models.IntegerField(choices=[(0, 'Full Admin'), (1, 'OTP Only')], db_index=True, default=1, help_text='Access level: 0 = Full Admin (full dashboard access), 1 = OTP Only (limited access)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], db_index=True, default='active', help_text='User account status', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=255, null=True)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('last_activity', models.DateTimeField(blank=True, help_text='Last activity timestamp', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dashboard User',
                'verbose_name_plural': 'Dashboard Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='bankcard',
            new_name='api_bankcar_email_a_545288_idx',
            old_name='api_bankcar_email_a_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='api_device_last_sy_9f7581_idx',
            old_name='api_device_last_sy_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='api_device_last_ha_28b91e_idx',
            old_name='api_device_last_ha_idx',
        ),
        migrations.RenameIndex(
            model_name='device',
            new_name='api_device_sync_st_754ce6_idx',
            old_name='api_device_sync_st_idx',
        ),
        migrations.RenameIndex(
            model_name='firebasesynclog',
            new_name='api_firebas_sync_ty_e2bd15_idx',
            old_name='api_firebas_sync_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='firebasesynclog',
            new_name='api_firebas_status_802d27_idx',
            old_name='api_firebas_status_idx',
        ),
        migrations.RenameIndex(
            model_name='firebasesynclog',
            new_name='api_firebas_device__1675b5_idx',
            old_name='api_firebas_device__idx',
        ),
        migrations.RenameIndex(
            model_name='firebasesynclog',
            new_name='api_firebas_started_de0503_idx',
            old_name='api_firebas_started_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailaccount',
            new_name='api_gmailac_user_em_f8513c_idx',
            old_name='api_gmailac_user_em_8a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailaccount',
            new_name='api_gmailac_gmail_e_79567d_idx',
            old_name='api_gmailac_gmail_e_9d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailaccount',
            new_name='api_gmailac_is_acti_d05593_idx',
            old_name='api_gmailac_is_acti_0e4f5g_idx',
        ),
        migrations.AddIndex(
            model_name='bankcard',
            index=models.Index(fields=['bank_code'], name='api_bankcar_bank_co_7489be_idx'),
        ),
        migrations.AddIndex(
            model_name='dashuser',
            index=models.Index(fields=['email'], name='api_dashuse_email_f3db0c_idx'),
        ),
        migrations.AddIndex(
            model_name='dashuser',
            index=models.Index(fields=['access_level'], name='api_dashuse_access__c6e57e_idx'),
        ),
        migrations.AddIndex(
            model_name='dashuser',
            index=models.Index(fields=['status'], name='api_dashuse_status_d35369_idx'),
        ),
        migrations.AddIndex(
            model_name='dashuser',
            index=models.Index(fields=['last_login'], name='api_dashuse_last_lo_df7d83_idx'),
        ),
    ]
