# Generated by Django 5.0.1 on 2026-01-24 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dashuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(db_index=True, help_text='Sender of the original message', max_length=50)),
                ('reply_message', models.TextField(help_text='Message sent as auto-reply')),
                ('original_timestamp', models.BigIntegerField(db_index=True, help_text='Timestamp of original message')),
                ('replied_at', models.BigIntegerField(db_index=True, help_text='Timestamp when reply was sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_logs', to='api.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'sender'], name='api_autorep_device__f6f3ad_idx'), models.Index(fields=['created_at'], name='api_autorep_created_2ee6e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(db_index=True, help_text='Command name (e.g., sendSms, updateApk)', max_length=100)),
                ('value', models.TextField(blank=True, help_text='Command parameters or data', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if command failed', null=True)),
                ('received_at', models.BigIntegerField(blank=True, help_text='Timestamp when APK received the command', null=True)),
                ('executed_at', models.BigIntegerField(blank=True, help_text='Timestamp when execution finished', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='command_logs', to='api.device')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'command'], name='api_command_device__8efb5b_idx'), models.Index(fields=['status'], name='api_command_status_f6bee4_idx'), models.Index(fields=['created_at'], name='api_command_created_02b957_idx')],
            },
        ),
    ]
