# Generated by Django 5.0.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_autoreplylog_commandlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                db_index=True,
                help_text='Dashboard user (e.g. admin@fastpay.com) this device is assigned to',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_devices',
                to='api.dashuser',
            ),
        ),
    ]
