# Generated by Django 5.0.1

from django.db import migrations, models


def migrate_assigned_to_data(apps, schema_editor):
    """
    Migrate data from ForeignKey assigned_to to ManyToMany assigned_to.
    For each device with an assigned_to ForeignKey, add that user to the ManyToMany field.
    """
    Device = apps.get_model('api', 'Device')
    DashUser = apps.get_model('api', 'DashUser')
    
    # Get all devices that have an assigned_to ForeignKey value
    # After renaming, the old field is now 'assigned_to_old'
    for device in Device.objects.all():
        # Check if device has an assigned user via the old ForeignKey
        old_assigned_to = getattr(device, 'assigned_to_old', None)
        if old_assigned_to:
            # Add user to the new ManyToMany field
            device.assigned_to_new.add(old_assigned_to)


def reverse_migrate_assigned_to_data(apps, schema_editor):
    """
    Reverse migration: Take first user from ManyToMany and set as ForeignKey.
    Note: This will lose data if a device has multiple users assigned.
    """
    Device = apps.get_model('api', 'Device')
    
    for device in Device.objects.all():
        # Get the first assigned user (if any)
        assigned_users = device.assigned_to_new.all()
        if assigned_users.exists():
            # Set the first user as the ForeignKey value
            device.assigned_to_old = assigned_users.first()
            device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_assigned_to'),
    ]

    operations = [
        # Step 1: Rename the old ForeignKey field temporarily
        migrations.RenameField(
            model_name='device',
            old_name='assigned_to',
            new_name='assigned_to_old',
        ),
        
        # Step 2: Create the new ManyToMany field with temporary name
        migrations.AddField(
            model_name='device',
            name='assigned_to_new',
            field=models.ManyToManyField(
                blank=True,
                related_name='assigned_devices',
                to='api.dashuser',
                help_text='Dashboard users (e.g. admin@fastpay.com) this device is assigned to. Multiple users can be assigned to the same device.',
            ),
        ),
        
        # Step 3: Migrate data from ForeignKey to ManyToMany
        migrations.RunPython(
            migrate_assigned_to_data,
            reverse_migrate_assigned_to_data,
        ),
        
        # Step 4: Remove the old ForeignKey field
        migrations.RemoveField(
            model_name='device',
            name='assigned_to_old',
        ),
        
        # Step 5: Rename the ManyToMany field to the final name
        migrations.RenameField(
            model_name='device',
            old_name='assigned_to_new',
            new_name='assigned_to',
        ),
    ]
