# Generated by Django 5.0.1 on 2026-01-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_change_assigned_to_to_manytomany'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, db_index=True, default='', help_text='Device Android ID (may be empty if unknown before activation)', max_length=255)),
                ('code_attempted', models.CharField(blank=True, db_index=True, help_text='Activation code or phone number attempted', max_length=255, null=True)),
                ('mode', models.CharField(choices=[('testing', 'Testing'), ('running', 'Running')], db_index=True, default='running', help_text='Activation mode: testing (phone) or running (code)', max_length=20)),
                ('error_type', models.CharField(blank=True, db_index=True, help_text='Short error category (e.g. validation, network, bank_code)', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context (e.g. stack trace, response codes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activation Failure Log',
                'verbose_name_plural': 'Activation Failure Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device_id', '-created_at'], name='api_activat_device__94be61_idx'), models.Index(fields=['mode', '-created_at'], name='api_activat_mode_a6ae43_idx'), models.Index(fields=['error_type', '-created_at'], name='api_activat_error_t_33700b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApiRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('path', models.CharField(db_index=True, max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('user_identifier', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['method', '-created_at'], name='api_apirequ_method_b10d5c_idx'), models.Index(fields=['status_code', '-created_at'], name='api_apirequ_status__c723e6_idx'), models.Index(fields=['-created_at'], name='api_apirequ_created_3c70de_idx')],
            },
        ),
    ]
