# Generated by Django 5.0.1 on 2026-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_activation_failure_and_api_request_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, help_text='Email of the user who performed the activity', max_length=254)),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_reset', 'Password Reset'), ('profile_update', 'Profile Update'), ('access_level_change', 'Access Level Change'), ('user_created', 'User Created'), ('user_deleted', 'User Deleted')], db_index=True, help_text='Type of activity performed', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the activity was performed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the activity')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_email', '-created_at'], name='api_activit_user_em_b391e2_idx'), models.Index(fields=['activity_type', '-created_at'], name='api_activit_activit_a0d6f0_idx'), models.Index(fields=['-created_at'], name='api_activit_created_011954_idx')],
            },
        ),
    ]
