# Generated by Django 5.0.1 on 2026-01-29 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_webhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='captureitem',
            new_name='api_capture_source_56d0d0_idx',
            old_name='api_captur_source_7c82a4_idx',
        ),
        migrations.RenameIndex(
            model_name='captureitem',
            new_name='api_capture_user_em_77c1ad_idx',
            old_name='api_captur_user_e_50f9a2_idx',
        ),
        migrations.RenameIndex(
            model_name='captureitem',
            new_name='api_capture_status_74715d_idx',
            old_name='api_captur_status_12d87e_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='api_webhook_event_t_2bff99_idx',
            old_name='api_webhoo_event_t_15f9a2_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='api_webhook_path_0da213_idx',
            old_name='api_webhoo_path_8ab03c_idx',
        ),
    ]
