#!/bin/bash
echo "=== FastPay Backend - Capacity Status ==="
echo ""
echo "System Resources:"
echo "CPU Cores: $(nproc)"
echo "Total RAM: $(free -h | grep Mem | awk '{print $2}')"
echo "Available RAM: $(free -h | grep Mem | awk '{print $7}')"
echo "Load Average: $(uptime | awk -F'load average:' '{print $2}')"
echo ""
echo "Docker Containers:"
docker-compose ps --format "table {{.Name}}\t{{.Status}}"
echo ""
echo "Database Connections:"
docker-compose exec -T db psql -U fastpay_user -d fastpay_db -c "SELECT count(*) as active FROM pg_stat_activity WHERE datname = 'fastpay_db';" 2>/dev/null | grep -E "active|row"
echo ""
echo "Current Configuration:"
echo "- Gunicorn: 4 workers × 2 threads = 8 concurrent requests"
echo "- Nginx: 2 workers × 1024 connections = 2048 max connections"
echo "- PostgreSQL: 100 max connections"
echo ""
echo "Estimated Capacity:"
echo "- Concurrent Requests: 8"
echo "- Requests/Second: ~30-40 RPS"
echo "- Daily Capacity: ~2.5-3.5M requests/day"
